### ISSUE TITLE
Identify services on non standard ports?

### ISSUE THREAD

**Issue by dobin** [kudelskisecurity/scannerl#1]
The "port" appears to be a hard requirement for a scannerl module. 

What, for example, if I want to identify MySQL on non-standard ports. Is, or will be, scannerl suited for this?

**Comment by deadc0de6** [comment]
absolutely, as documented [here](https://github.com/kudelskisecurity/scannerl/wiki/Usage#port-specification) the port can be specified using three different ways:
* (1) through the module itself with the directive `-define(PORT, ...)` - a good practice would be to set the default port of the service there
* (2) through the command line switch `-p <port>` when invoking scannerl
* (3) on the target directly like for example `<target>:<port>` - this allows to target multiple hosts on different ports with the same fingerprinting module

(3) overwrites (2) which overwrites (1)

**Comment by deadc0de6** [comment]
For example if you'd like to target localhost on a different port like `1234` for example, you could do for MySQL:

```
./scannerl -m fp_mysql_greeting -p 1234 -f 127.0.0.1 
```

or 
```
./scannerl -m fp_mysql_greeting -f 127.0.0.1:1234
```

**Comment by dobin** [comment]
Awesome, thx. Havent seen that part of the documentation. 

My use case is more in internal pentests: For example I found an open port 6666, and i want to quickly identify what service it is (the usual; http, https, sql server, whatever. Sometimes in a class B network with a lot of services on nonstandard ports). Trying to evaluate how goot scannerl is suited for this.

**Comment by deadc0de6** [comment]
Currently there's no specific module for doing this. You would need to run them all against your targets/ports however it would be possible to implement a fp module that does this: matching the received payload against a list of signatures for example.

As long as the list of signatures is available, it shouldn't be that hard to implement ...

**Comment by dobin** [comment]
Hmm i see, have to specify all modules with "-m", separated by commas. 

Maybe a "-m all" would be useful? :-)

**Comment by deadc0de6** [comment]
Actually scannerl doesn't currently support the use of multiple fp modules for one scan session, only one module can be specified through the `-m` switch. You would have to run them one by one as a different scan session.
But for a `/16` range, it should be pretty fast if you distribute your work.

**Comment by dobin** [comment]
Oh, i've misread (its "arguments separated by commas", not "modules are separated by commas". Anyhow, thanks for the answers.
